language: python
python:
  - 2.7
  # command to install dependencies
install:
    - pip install pytest
    - pip install unittest2
    - pip install tweepy
    - pip install folium==0.2.1
#command to run tests
script: 
       - python -m pytest -v test1.py
       - python -m pytest -v test2.py
       - python -m pytest -v test3.py
       - python -m pytest -v test4.py
branches:
  only:
    - master
